DROP TABLE `sys_function`;

CREATE TABLE `sys_function` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '序号',
  `VERSION` int(11) DEFAULT '0' COMMENT '版本编号',
  `FUNCTION_ID` varchar(32) NOT NULL COMMENT '菜单编码',
  `FUNCTION_NAME` varchar(64) NOT NULL COMMENT '菜单名称',
  `FUNCTION_TYPE` smallint(6) NOT NULL COMMENT '菜单类型',
  `FUNCTION_PARENT_ID` varchar(32) DEFAULT NULL COMMENT '父菜单编码',
  `FUNCTION_URL` varchar(64) DEFAULT NULL COMMENT '菜单URL',
  `ORDER_NO` int(11) NOT NULL COMMENT '排序编码',
  `FUNCTION_LOGO` varchar(64) DEFAULT NULL COMMENT '图标',
  `BUTTON_POSITION` varchar(64) DEFAULT NULL COMMENT '按钮位置',
  `REMARK` varchar(200) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=511 DEFAULT CHARSET=utf8 COMMENT='权限';


INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (460,0,'1','权限管理',1,'-1','#',1,'fa-diamond',null,'1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (461,0,'2','报表管理',1,'-1','#',2,'fa-bar-chart',null,'1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (462,0,'3','系统管理',1,'-1','#',3,'fa-money',null,'1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (463,0,'4','日志管理',1,'-1','#',4,'fa-map-o',null,'1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (464,0,'5','用户管理',2,'1','./modules/authority/user/user.html',101,'',null,'1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (465,0,'6','角色管理',2,'1','./modules/authority/role/role.html',102,'',null,'1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (466,0,'7','机构管理',2,'1','./modules/authority/group/group.html',103,'',null,'1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (467,0,'8','权限管理',2,'1','./modules/authority/function/function.html',104,'',null,'1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (468,0,'9','demo',2,'2','./modules/report/demo/report.html',201,'',null,'1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (470,2,'11','运行监控',2,'3','/druid/index.html',302,'','','1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (471,0,'12','日志查询',2,'4','./modules/log/log/log.html',401,'',null,'1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (472,0,'13','添加',3,'5','',501,'','userForm.add_table','1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (473,0,'14','编辑',3,'5','',502,'','userForm.update_table','1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (474,0,'15','删除',3,'5','',503,'','userForm.remove_table','1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (475,0,'16','密码重置',3,'5','',504,'','userForm.password_reset','1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (476,0,'17','导入',3,'5','',505,'','userForm.import_table','1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (477,0,'18','导出',3,'5','',506,'','userForm.export_table','1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (478,0,'19','配置机构',3,'5','',507,'','userForm.configure_group','1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (479,0,'20','配置角色',3,'5','',508,'','userForm.configure_role','1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (480,0,'21','查询',3,'5','',509,'','userForm.query_table','1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (481,0,'22','重置',3,'5','',510,'','userForm.reset_form','1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (482,0,'23','数据初始化',3,'5','',511,'','userForm.reset_data','1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (483,0,'24','添加',3,'6','',601,'','roleForm.add_table','1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (484,0,'25','编辑',3,'6','',602,'','roleForm.update_table','1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (485,0,'26','删除',3,'6','',603,'','roleForm.remove_table','1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (486,0,'27','导入',3,'6','',604,'','roleForm.import_table','1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (487,0,'28','导出',3,'6','',604,'','roleForm.export_table','1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (488,0,'29','配置权限',3,'6','',605,'','roleForm.configure_function','1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (489,0,'30','查询',3,'6','',606,'','roleForm.query_table','1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (490,0,'31','重置',3,'6','',607,'','roleForm.reset_form','1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (491,0,'32','数据初始化',3,'6','',608,'','roleForm.reset_data','1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (492,0,'33','添加',3,'7','',701,'','groupForm.add_table','1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (493,0,'34','编辑',3,'7','',702,'','groupForm.update_table','1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (494,0,'35','删除',3,'7','',703,'','groupForm.remove_table','1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (495,0,'36','配置角色',3,'7','',704,'','groupForm.configure_function','1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (496,0,'37','查询',3,'7','',705,'','groupForm.query_table','1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (497,0,'38','重置',3,'7','',706,'','groupForm.reset_form','1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (498,0,'39','数据初始化',3,'7','',707,'','groupForm.reset_data','1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (499,0,'40','添加',3,'8','',801,'','functionForm.add_table','1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (500,0,'41','编辑',3,'8','',802,'','functionForm.update_table','1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (501,0,'42','删除',3,'8','',803,'','functionForm.remove_table','1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (502,0,'43','查询',3,'8','',804,'','functionForm.query_table','1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (503,0,'44','重置',3,'8','',805,'','functionForm.reset_form','1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (504,0,'45','数据初始化',3,'8','',806,'','functionForm.reset_data','1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (505,0,'46','查询',3,'9','',901,'','reportForm.query_table','1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (506,0,'47','重置',3,'9','',902,'','reportForm.reset_form','1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (507,0,'48','查询',3,'12','',1201,'','logForm.query_table','1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (508,0,'49','重置',3,'12','',1203,'','logForm.reset_form','1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (509,0,'50','数据初始化',3,'12','',1203,'','logForm.reset_data','1');
INSERT INTO sys_function(ID,VERSION,FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_PARENT_ID,FUNCTION_URL,ORDER_NO,FUNCTION_LOGO,BUTTON_POSITION,REMARK) VALUES (510,4,'51','生成代码',2,'3','./modules/system/code/code.html',303,'','-','');

DROP TABLE `sys_group_role`;

CREATE TABLE `sys_group_role` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '序号',
  `VERSION` int(11) NOT NULL DEFAULT '0' COMMENT '版本编号',
  `GROUP_ID` varchar(32) NOT NULL COMMENT '机构编码',
  `ROLE_ID` varchar(32) NOT NULL COMMENT '角色编码',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='机构角色';

DROP TABLE `sys_group`;

CREATE TABLE `sys_group` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '序号',
  `VERSION` int(11) NOT NULL DEFAULT '0' COMMENT '版本编号',
  `GROUP_ID` varchar(32) NOT NULL COMMENT '机构编码',
  `GROUP_NAME` varchar(32) NOT NULL COMMENT '机构名称',
  `GROUP_LEVER` smallint(6) NOT NULL COMMENT '机构层号',
  `GROUP_PARENT_ID` varchar(32) DEFAULT NULL COMMENT '父机构编码',
  `ORDER_NO` int(11) NOT NULL COMMENT '排序编码',
  `REMARK` varchar(200) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8 COMMENT='机构';


INSERT INTO sys_group(ID,VERSION,GROUP_ID,GROUP_NAME,GROUP_LEVER,GROUP_PARENT_ID,ORDER_NO,REMARK) VALUES (5,0,'1','1号线',1,null,1,'');
INSERT INTO sys_group(ID,VERSION,GROUP_ID,GROUP_NAME,GROUP_LEVER,GROUP_PARENT_ID,ORDER_NO,REMARK) VALUES (6,0,'2','车站1',2,'1',1,'');
INSERT INTO sys_group(ID,VERSION,GROUP_ID,GROUP_NAME,GROUP_LEVER,GROUP_PARENT_ID,ORDER_NO,REMARK) VALUES (7,0,'3','车站2',2,'1',2,'');
INSERT INTO sys_group(ID,VERSION,GROUP_ID,GROUP_NAME,GROUP_LEVER,GROUP_PARENT_ID,ORDER_NO,REMARK) VALUES (10,2,'4','4',4,'4',4,'4');
INSERT INTO sys_group(ID,VERSION,GROUP_ID,GROUP_NAME,GROUP_LEVER,GROUP_PARENT_ID,ORDER_NO,REMARK) VALUES (12,0,'5','5',5,'5',5,'');

DROP TABLE `sys_log`;

CREATE TABLE `sys_log` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '序号',
  `VERSION` int(11) NOT NULL DEFAULT '0' COMMENT '版本编号',
  `OCCUR_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '发生时间',
  `OPERATOR_ID` varchar(32) NOT NULL COMMENT '操作员',
  `LOG_TYPE` smallint(6) NOT NULL COMMENT '日志类型',
  `LOG_LEVEL` smallint(6) NOT NULL COMMENT '日志等级',
  `LOG_DESC` varchar(32) DEFAULT NULL COMMENT '日志描述',
  `IP_ADDRESS` varchar(32) DEFAULT NULL COMMENT '操作员IP',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=197 DEFAULT CHARSET=utf8 COMMENT='日志';

DROP TABLE `sys_role_function`;

CREATE TABLE `sys_role_function` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '序号',
  `VERSION` int(11) NOT NULL DEFAULT '0' COMMENT '版本编号',
  `ROLE_ID` varchar(32) NOT NULL COMMENT '角色编码',
  `FUNCTION_ID` varchar(32) NOT NULL COMMENT '菜单编码',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=331 DEFAULT CHARSET=utf8 COMMENT='角色权限';


INSERT INTO sys_role_function(ID,VERSION,ROLE_ID,FUNCTION_ID) VALUES (293,0,'1','13');
INSERT INTO sys_role_function(ID,VERSION,ROLE_ID,FUNCTION_ID) VALUES (294,0,'1','14');
INSERT INTO sys_role_function(ID,VERSION,ROLE_ID,FUNCTION_ID) VALUES (295,0,'1','15');
INSERT INTO sys_role_function(ID,VERSION,ROLE_ID,FUNCTION_ID) VALUES (296,0,'1','16');
INSERT INTO sys_role_function(ID,VERSION,ROLE_ID,FUNCTION_ID) VALUES (297,0,'1','17');
INSERT INTO sys_role_function(ID,VERSION,ROLE_ID,FUNCTION_ID) VALUES (298,0,'1','18');
INSERT INTO sys_role_function(ID,VERSION,ROLE_ID,FUNCTION_ID) VALUES (299,0,'1','19');
INSERT INTO sys_role_function(ID,VERSION,ROLE_ID,FUNCTION_ID) VALUES (300,0,'1','20');
INSERT INTO sys_role_function(ID,VERSION,ROLE_ID,FUNCTION_ID) VALUES (301,0,'1','21');
INSERT INTO sys_role_function(ID,VERSION,ROLE_ID,FUNCTION_ID) VALUES (302,0,'1','22');
INSERT INTO sys_role_function(ID,VERSION,ROLE_ID,FUNCTION_ID) VALUES (303,0,'1','23');
INSERT INTO sys_role_function(ID,VERSION,ROLE_ID,FUNCTION_ID) VALUES (304,0,'1','5');
INSERT INTO sys_role_function(ID,VERSION,ROLE_ID,FUNCTION_ID) VALUES (305,0,'1','24');
INSERT INTO sys_role_function(ID,VERSION,ROLE_ID,FUNCTION_ID) VALUES (306,0,'1','25');
INSERT INTO sys_role_function(ID,VERSION,ROLE_ID,FUNCTION_ID) VALUES (307,0,'1','26');
INSERT INTO sys_role_function(ID,VERSION,ROLE_ID,FUNCTION_ID) VALUES (308,0,'1','27');
INSERT INTO sys_role_function(ID,VERSION,ROLE_ID,FUNCTION_ID) VALUES (309,0,'1','28');
INSERT INTO sys_role_function(ID,VERSION,ROLE_ID,FUNCTION_ID) VALUES (310,0,'1','29');
INSERT INTO sys_role_function(ID,VERSION,ROLE_ID,FUNCTION_ID) VALUES (311,0,'1','30');
INSERT INTO sys_role_function(ID,VERSION,ROLE_ID,FUNCTION_ID) VALUES (312,0,'1','31');
INSERT INTO sys_role_function(ID,VERSION,ROLE_ID,FUNCTION_ID) VALUES (313,0,'1','32');
INSERT INTO sys_role_function(ID,VERSION,ROLE_ID,FUNCTION_ID) VALUES (314,0,'1','6');
INSERT INTO sys_role_function(ID,VERSION,ROLE_ID,FUNCTION_ID) VALUES (315,0,'1','33');
INSERT INTO sys_role_function(ID,VERSION,ROLE_ID,FUNCTION_ID) VALUES (316,0,'1','34');
INSERT INTO sys_role_function(ID,VERSION,ROLE_ID,FUNCTION_ID) VALUES (317,0,'1','35');
INSERT INTO sys_role_function(ID,VERSION,ROLE_ID,FUNCTION_ID) VALUES (318,0,'1','36');
INSERT INTO sys_role_function(ID,VERSION,ROLE_ID,FUNCTION_ID) VALUES (319,0,'1','37');
INSERT INTO sys_role_function(ID,VERSION,ROLE_ID,FUNCTION_ID) VALUES (320,0,'1','38');
INSERT INTO sys_role_function(ID,VERSION,ROLE_ID,FUNCTION_ID) VALUES (321,0,'1','39');
INSERT INTO sys_role_function(ID,VERSION,ROLE_ID,FUNCTION_ID) VALUES (322,0,'1','7');
INSERT INTO sys_role_function(ID,VERSION,ROLE_ID,FUNCTION_ID) VALUES (323,0,'1','40');
INSERT INTO sys_role_function(ID,VERSION,ROLE_ID,FUNCTION_ID) VALUES (324,0,'1','41');
INSERT INTO sys_role_function(ID,VERSION,ROLE_ID,FUNCTION_ID) VALUES (325,0,'1','42');
INSERT INTO sys_role_function(ID,VERSION,ROLE_ID,FUNCTION_ID) VALUES (326,0,'1','43');
INSERT INTO sys_role_function(ID,VERSION,ROLE_ID,FUNCTION_ID) VALUES (327,0,'1','44');
INSERT INTO sys_role_function(ID,VERSION,ROLE_ID,FUNCTION_ID) VALUES (328,0,'1','45');
INSERT INTO sys_role_function(ID,VERSION,ROLE_ID,FUNCTION_ID) VALUES (329,0,'1','8');
INSERT INTO sys_role_function(ID,VERSION,ROLE_ID,FUNCTION_ID) VALUES (330,0,'1','1');

DROP TABLE `sys_role`;

CREATE TABLE `sys_role` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '序号',
  `VERSION` int(11) NOT NULL DEFAULT '0' COMMENT '版本编号',
  `ROLE_ID` varchar(32) NOT NULL COMMENT '角色编码',
  `ROLE_DESC` varchar(32) NOT NULL COMMENT '角色描述',
  `REMARK` varchar(200) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `u_index_role_id` (`ROLE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COMMENT='角色';


INSERT INTO sys_role(ID,VERSION,ROLE_ID,ROLE_DESC,REMARK) VALUES (3,0,'0','超级管理员','1');
INSERT INTO sys_role(ID,VERSION,ROLE_ID,ROLE_DESC,REMARK) VALUES (4,2,'1','一号线','2');

DROP TABLE `sys_user_group`;

CREATE TABLE `sys_user_group` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '序号',
  `VERSION` int(11) NOT NULL DEFAULT '0' COMMENT '版本编号',
  `USER_ID` varchar(32) NOT NULL COMMENT '用户编码',
  `GROUP_ID` varchar(32) NOT NULL COMMENT '机构编码',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 COMMENT='用户机构';


INSERT INTO sys_user_group(ID,VERSION,USER_ID,GROUP_ID) VALUES (3,0,'1','2');

DROP TABLE `sys_user_role`;

CREATE TABLE `sys_user_role` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '序号',
  `VERSION` int(11) NOT NULL DEFAULT '0' COMMENT '版本编号',
  `USER_ID` varchar(32) NOT NULL COMMENT '用户编码',
  `ROLE_ID` varchar(32) NOT NULL COMMENT '角色编码',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COMMENT='用户角色';


INSERT INTO sys_user_role(ID,VERSION,USER_ID,ROLE_ID) VALUES (2,0,'1','1');


DROP TABLE `sys_user`;

CREATE TABLE `sys_user` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '序号',
  `VERSION` int(11) NOT NULL DEFAULT '0' COMMENT '版本编号',
  `USER_ID` varchar(32) NOT NULL COMMENT '用户编码',
  `USER_PASS_WORD` varchar(32) NOT NULL COMMENT '用户密码',
  `USER_NAME` varchar(32) NOT NULL COMMENT '用户名称',
  `USER_TELEPHONE` varchar(32) DEFAULT NULL COMMENT '电话号码',
  `USER_EMAIL` varchar(32) DEFAULT NULL COMMENT '用户邮箱',
  `USER_BIRTHDAY` date DEFAULT NULL COMMENT '出生日期',
  `USER_ID_CARD` varchar(64) DEFAULT NULL COMMENT '身份证号',
  `IF_VALID` smallint(6) DEFAULT NULL COMMENT '是否有效',
  `USER_VALIDITY_PERIOD` date DEFAULT NULL COMMENT '用户有效期',
  `PW_VALIDITY_PERIOD` date DEFAULT NULL COMMENT '密码有效期',
  `REMARK` varchar(200) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8 COMMENT='用户';


INSERT INTO sys_user(ID,VERSION,USER_ID,USER_PASS_WORD,USER_NAME,USER_TELEPHONE,USER_EMAIL,USER_BIRTHDAY,USER_ID_CARD,IF_VALID,USER_VALIDITY_PERIOD,PW_VALIDITY_PERIOD,REMARK) VALUES (4,0,'admin','21232f297a57a5a743894a0e4a801fc3','超级管理员','123456789','liuliu@163.com','2017-10-27 00:00:00','111111',1,'2017-10-27 00:00:00','2017-10-27 00:00:00','1');
INSERT INTO sys_user(ID,VERSION,USER_ID,USER_PASS_WORD,USER_NAME,USER_TELEPHONE,USER_EMAIL,USER_BIRTHDAY,USER_ID_CARD,IF_VALID,USER_VALIDITY_PERIOD,PW_VALIDITY_PERIOD,REMARK) VALUES (5,4,'1','c4ca4238a0b923820dcc509a6f75849b','2','123456789','liuliu@163.com','2017-10-27 00:00:00','111111',1,'2017-10-27 00:00:00','2017-10-27 00:00:00','1');
